---
# Per environment values which override defaults in hmpps-manage-online-check-ins-ui/values.yaml

generic-service:
  ingress:
    host: manage-online-check-ins-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-online-check-ins-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"
    COMPONENT_API_URL: "https://probation-frontend-components.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: "PRODUCTION"

generic-prometheus-alerts:
  alertSeverity: warning
