generic-service:
  replicaCount: 2

  ingress:
    host: manage-online-check-ins-test.hmpps.service.justice.gov.uk
    className: modsec-non-prod

  env:
    INGRESS_URL: 'https://manage-online-check-ins-test.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-dev.prison.service.justice.gov.uk'
    ESUPERVISION_API_URL: 'https://esupervision-api-test.hmpps.service.justice.gov.uk'
    POP_API_URL: 'https://people-on-probation-api-dev.hmpps.service.justice.gov.uk'
    V2_FEEDBACK_URL: 'https://probation-check-in-test.hmpps.service.justice.gov.uk/feedback'
    COMPONENT_API_URL: "https://probation-frontend-components-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: TEST
    AUDIT_ENABLED: 'false'
    AUTHORISED_USER_ROLES: 'ROLE_ESUPERVISION__PRACTITIONER__RW'

generic-prometheus-alerts:
  alertSeverity: hmpps_esupervision_alerts_nonprod
